name: performance_test

on:
  schedule:
    - cron: "0 0 * * *"
      timezone: "America/Vancouver"
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  # This logic is based on the discussion here (and the links within):
  # https://github.com/orgs/community/discussions/27128
  #
  check_for_new_commits:
    name: Check for commits in the last 24 hours
    runs-on: ubuntu-latest
    outputs:
      num_new_commits: ${{ steps.count_new_commits.outputs.num_new_commits }}
    steps:
      - uses: actions/checkout@v6

      - id: count_new_commits
        run: echo "num_new_commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"


  run:
    name: Python ${{ matrix.python-version }} Performance Tests
    runs-on: ${{ matrix.os }}

    needs: check_for_new_commits
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check_for_new_commits.outputs.num_new_commits > 0 }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt update && apt install yamllint
          pip install uv

      - name: Run slow tests
        run: uv run pytest --memray -m slow --no-cov
